// <auto-generated />
using System;
using AtrevidoFitness.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtrevidoFitness.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Who can lose the most weight in a month?",
                            EndDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPublic = true,
                            Rules = "Have fun",
                            StartDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            Title = "30-Day Fitness Challenge"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Who can lose the most weight in a week?",
                            EndDate = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsPublic = true,
                            Rules = "Have fun",
                            StartDate = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            Title = "Weekly Fitness Challenge"
                        });
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.ChallengeParticipant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId", "ChallengeId")
                        .IsUnique();

                    b.ToTable("ChallengeParticipants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChallengeId = 1,
                            JoinedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            ChallengeId = 2,
                            JoinedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            ChallengeId = 1,
                            JoinedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            ChallengeId = 2,
                            JoinedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 3
                        },
                        new
                        {
                            Id = 5,
                            ChallengeId = 1,
                            JoinedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 4
                        },
                        new
                        {
                            Id = 6,
                            ChallengeId = 2,
                            JoinedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 4
                        },
                        new
                        {
                            Id = 7,
                            ChallengeId = 1,
                            JoinedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 5
                        },
                        new
                        {
                            Id = 8,
                            ChallengeId = 2,
                            JoinedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = 5
                        });
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.NutritionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PdfBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfFileSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PdfUploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.ProgressEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ArmCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ChestCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("HipsCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ThighCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WaistCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.HasIndex("UserId");

                    b.ToTable("ProgressEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArmCm = 28.00m,
                            ChallengeId = 1,
                            ChestCm = 88.00m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryDate = new DateOnly(2026, 4, 1),
                            HipsCm = 96.00m,
                            Notes = "Starting measurements",
                            ThighCm = 54.00m,
                            UserId = 2,
                            WaistCm = 78.00m,
                            WeightKg = 72.50m
                        },
                        new
                        {
                            Id = 2,
                            ArmCm = 27.80m,
                            ChallengeId = 1,
                            ChestCm = 87.50m,
                            CreatedAt = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryDate = new DateOnly(2026, 4, 10),
                            HipsCm = 95.00m,
                            Notes = "Feeling great!",
                            ThighCm = 53.50m,
                            UserId = 2,
                            WaistCm = 77.00m,
                            WeightKg = 71.20m
                        },
                        new
                        {
                            Id = 3,
                            ArmCm = 27.50m,
                            ChallengeId = 1,
                            ChestCm = 87.00m,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryDate = new DateOnly(2026, 4, 20),
                            HipsCm = 94.50m,
                            Notes = "Consistent progress",
                            ThighCm = 53.00m,
                            UserId = 2,
                            WaistCm = 76.00m,
                            WeightKg = 70.10m
                        },
                        new
                        {
                            Id = 4,
                            ArmCm = 26.50m,
                            ChallengeId = 1,
                            ChestCm = 85.00m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryDate = new DateOnly(2026, 4, 1),
                            HipsCm = 92.00m,
                            Notes = "Starting measurements",
                            ThighCm = 51.00m,
                            UserId = 3,
                            WaistCm = 74.00m,
                            WeightKg = 68.00m
                        },
                        new
                        {
                            Id = 5,
                            ArmCm = 26.00m,
                            ChallengeId = 1,
                            ChestCm = 84.50m,
                            CreatedAt = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryDate = new DateOnly(2026, 4, 15),
                            HipsCm = 91.00m,
                            Notes = "Good progress",
                            ThighCm = 50.50m,
                            UserId = 3,
                            WaistCm = 73.00m,
                            WeightKg = 66.80m
                        },
                        new
                        {
                            Id = 6,
                            ArmCm = 29.00m,
                            ChallengeId = 1,
                            ChestCm = 90.00m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryDate = new DateOnly(2026, 4, 1),
                            HipsCm = 98.00m,
                            Notes = "Starting measurements",
                            ThighCm = 56.00m,
                            UserId = 4,
                            WaistCm = 80.00m,
                            WeightKg = 75.00m
                        },
                        new
                        {
                            Id = 7,
                            ArmCm = 28.70m,
                            ChallengeId = 1,
                            ChestCm = 89.50m,
                            CreatedAt = new DateTime(2026, 4, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryDate = new DateOnly(2026, 4, 20),
                            HipsCm = 97.00m,
                            Notes = "Steady progress",
                            ThighCm = 55.50m,
                            UserId = 4,
                            WaistCm = 79.00m,
                            WeightKg = 73.50m
                        },
                        new
                        {
                            Id = 8,
                            ArmCm = 25.00m,
                            ChallengeId = 1,
                            ChestCm = 83.00m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryDate = new DateOnly(2026, 4, 1),
                            HipsCm = 89.00m,
                            Notes = "Starting measurements",
                            ThighCm = 49.00m,
                            UserId = 5,
                            WaistCm = 70.00m,
                            WeightKg = 65.00m
                        },
                        new
                        {
                            Id = 9,
                            ArmCm = 24.80m,
                            ChallengeId = 1,
                            ChestCm = 82.50m,
                            CreatedAt = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            EntryDate = new DateOnly(2026, 4, 18),
                            HipsCm = 88.50m,
                            Notes = "Feeling lighter",
                            ThighCm = 48.50m,
                            UserId = 5,
                            WaistCm = 69.50m,
                            WeightKg = 64.00m
                        });
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.TrainingRegistration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingSessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainingSessionId");

                    b.HasIndex("UserId", "TrainingSessionId", "SessionDate")
                        .IsUnique();

                    b.ToTable("TrainingRegistrations");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.TrainingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<int>("MinCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TrainingSessions");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "dika@atrevido.ba",
                            FirstName = "Dika",
                            IsActive = true,
                            LastName = "Admin",
                            PasswordHash = "$2a$11$9X54vtzpELoCeh3YGuLYje8yPBBh8.OiGu2Sw9YJivu/uPdaTMOZC",
                            Role = "Admin",
                            Username = "dika.admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sarah@atrevido.ba",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$nHqUhaTpSV6554EydEPaR.d3Agwj5cwCUdrYQWLD7tKo9O3g9e7l2",
                            Role = "Member",
                            Username = ""
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria@atrevido.ba",
                            FirstName = "Maria",
                            IsActive = true,
                            LastName = "Smith",
                            PasswordHash = "$2a$11$QJ/00BUdc5vNqHpjGWFaF.PZhIDoiH2FljheI7usFsG0zqlrDBOwm",
                            Role = "Member",
                            Username = ""
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jennifer@atrevido.ba",
                            FirstName = "Jennifer",
                            IsActive = true,
                            LastName = "Kane",
                            PasswordHash = "$2a$11$NbYzy8BZGFyDNNXpkmfwKO/fdn93wg1JJDXEaqXRt9wJy4iC/mdAS",
                            Role = "Member",
                            Username = ""
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "amanda@atrevido.ba",
                            FirstName = "Amanda",
                            IsActive = true,
                            LastName = "Ross",
                            PasswordHash = "$2a$11$K2dcCeJgViV0Zudaw4TFC.nhEMhD8KkODPUlSss2jB3ptSVZJFU9i",
                            Role = "Member",
                            Username = ""
                        });
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.UserTrainingMembership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("NutritionEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserTrainingMemberships");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.BlogPost", b =>
                {
                    b.HasOne("AtrevidoFitness.API.Models.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.ChallengeParticipant", b =>
                {
                    b.HasOne("AtrevidoFitness.API.Models.Entities.Challenge", "Challenge")
                        .WithMany("Participants")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtrevidoFitness.API.Models.Entities.User", "User")
                        .WithMany("ChallengeParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.NutritionPlan", b =>
                {
                    b.HasOne("AtrevidoFitness.API.Models.Entities.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedToUser");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.ProgressEntry", b =>
                {
                    b.HasOne("AtrevidoFitness.API.Models.Entities.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId");

                    b.HasOne("AtrevidoFitness.API.Models.Entities.User", "User")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.TrainingRegistration", b =>
                {
                    b.HasOne("AtrevidoFitness.API.Models.Entities.TrainingSession", "TrainingSession")
                        .WithMany("Registrations")
                        .HasForeignKey("TrainingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtrevidoFitness.API.Models.Entities.User", "User")
                        .WithMany("TrainingRegistrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrainingSession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.UserTrainingMembership", b =>
                {
                    b.HasOne("AtrevidoFitness.API.Models.Entities.User", "User")
                        .WithOne("TrainingMembership")
                        .HasForeignKey("AtrevidoFitness.API.Models.Entities.UserTrainingMembership", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.Challenge", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.TrainingSession", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("AtrevidoFitness.API.Models.Entities.User", b =>
                {
                    b.Navigation("ChallengeParticipations");

                    b.Navigation("ProgressEntries");

                    b.Navigation("TrainingMembership");

                    b.Navigation("TrainingRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
